Repository gabiduarte/awesome-techleads, pull requests merged in 2020-04, with the labels that each got.

#4 Book: Randical Candor - Kin Scott
  readme.md
Labels: melhoria

#5 Release It!: Michael T. Nygard
  readme.md
Labels: melhoria

#7 Faça tempo - Jake Knapp, John Zeratsky
  readme.md
Labels: melhoria

#6 A arte de dar feedback - Harvard Business Review
  readme.md
Labels: melhoria

#8 Remoção de conteúdo repetido
  readme.md
Labels: fix

#9 Adiciona slack criado por Michael Lopp
  readme.md
Labels: conteúdo

#10 Adiciona podcast Programming Leadership
  readme.md
Labels: conteúdo
